### ISSUE TITLE
Annyang not working

### ISSUE THREAD

**Issue by Omaley** [Veldrovive/MMM-Voice-Commands#1]
Hi,
Tried the plugin but unfortunately with no success. Is it compatible with MagicMirror2 ? I manage to make Annyang working on Chromium (web browser) but with MagicMirror the consol shows an error 'network'... Any idea ?

**Comment by Veldrovive** [comment]
Right, I don't know why I didn't put this in the readme. Chromium doesn't have the same access to the Chrome Speech API so you can't just use it by default. You can get access to it by [providing an api key](https://www.chromium.org/developers/how-tos/api-keys), but I made this module to be a really simple way to get speech recognition running. Therefore, I don't use electron and instead just have Magic Mirror run on chrome by using the `node serveronly` option.

**Comment by ronanversendaal** [comment]
Could you please still add this to the readme? (If it is still an issue)  I stumbled across this issue while checking all this repo's issues, but I was planning to use chromium as well, and it would be real nice for new users to know about this. Thanks in advance.

**Comment by Veldrovive** [comment]
It is already included in the readme. However, it is phrased as "annyang does not work when Magic Mirror is run using electron" since I assumed people would only be using chromium if they are using the electron wrapper. 
Should I instead state that chromium cannot be used?

**Comment by ronanversendaal** [comment]
Ah, yeah you cleared it up just now. I searched the readme again before posting my previous comment, but couldn't find it then. I guess it would be more clear that way. I could think of a case where a client (maybe another Raspberry pi - clientonly) would connect via Chromium.

**Comment by Veldrovive** [comment]
I've made it more clear now. I think it should suffice.

**Comment by ronanversendaal** [comment]
Indeed! Thanks again!
