### ISSUE TITLE
installation instruction

### ISSUE THREAD

**Issue by MichaelF1** [Veldrovive/MMM-Voice-Commands#2]
Man could you please help me with the installation. your instruction says:

`git clone https://github.com/Veldrovive/MMM-Voice-Commands.git`

Navigate into the installation and Install Dependencies.

`cd MMM-Page-Selector && npm i`

So should the last command be `cd MMM-Voice-Commands && npm install `

or do I need to install the moduel MMM-Page-Selector first and then make:

`cd MMM-Page-Selector && npm install ?`

regards

**Comment by Veldrovive** [comment]
Running the command `git clone https://github.com/Veldrovive/MMM-Voice-Commands.git` is actually installing the module. The next step is to install the dependencies so `cd MMM-Voice-Commands && npm install` is the last step.
As long as you are still inside the modules folder, then running `cd MMM-Page-Selector && npm i` will complete the installation and the module can then be used.

**Comment by cowboysdude** [comment]
`npm i` and `npm install` are the same ;)  I think that's what he was unsure of.   I'm going to put this through a work out tomorrow on my 32" touch mirror!  Looks great both modules that is!!  Great job!

**Comment by Veldrovive** [comment]
Ah, well in I hope and assume that the issue is solved now.
